### ISSUE TITLE
Failure When Converting Materials.

### ISSUE THREAD

**Issue by OFWModz** [kurotu/VRCQuestTools#1]
![image](https://user-images.githubusercontent.com/36628963/118946521-5e8fc480-b94e-11eb-9ecc-c5738860964e.png)

**Comment by kurotu** [comment]
Hi, would you apply this patch (https://github.com/kurotu/VRCQuestTools/commit/28c0cce9e90c2470dc07a8a9b21b9f87c1cf36dc) then try again? The patch shows more detailed error to research the problem.

**Comment by kurotu** [comment]
@OFWModz
Sadly the screenshot you posted is not enough to solve the problem. Would you try [v0.4.1](https://github.com/kurotu/VRCQuestTools/releases/tag/v0.4.1) and post a screenshot of error dialog? It would be helpful to know a reason of error.

**Comment by kurotu** [comment]
No longer active, closed.
