### ISSUE TITLE
Error when converting

### ISSUE THREAD

**Issue by KonstaVilkman** [kurotu/VRCQuestTools#11]
**Describe the bug**
Error when converting

**To Reproduce**
1. Press convert

**Expected behavior**
Make a new scene with the avi. Drag the avi into the tool. Select 512x512. Click convert

**Screenshots**
![image](https://github.com/kurotu/VRCQuestTools/assets/73310940/edaeec71-30b7-4b6d-ba86-68dfa81a378a)
![image](https://github.com/kurotu/VRCQuestTools/assets/73310940/0a9727f9-a4f6-4b4e-bfb8-e590adde5e12)

**Console log**
InvalidOperationException: Failed to convert a material "Springjoint X". See the previous error log for detail.
KRT.VRCQuestTools.Models.VRChat.AvatarConverter.GenrateToonLitTextures (UnityEngine.Material[] materials, System.String assetsDirectory, System.Int32 maxTextureSize, KRT.VRCQuestTools.Models.Unity.TextureGeneratorSetting setting, KRT.VRCQuestTools.Models.VRChat.AvatarConverter+TextureProgressCallback progressCallback) (at Packages/com.github.kurotu.vrc-quest-tools/Editor/Models/VRChat/AvatarConverter.cs:263)
KRT.VRCQuestTools.Models.VRChat.AvatarConverter.ConvertForQuest (KRT.VRCQuestTools.Models.VRChat.VRChatAvatar avatar, System.String assetsDirectory, KRT.VRCQuestTools.Models.ComponentRemover remover, KRT.VRCQuestTools.Models.VRChat.AvatarConverterSetting setting, KRT.VRCQuestTools.Models.VRChat.AvatarConverter+ProgressCallback progressCallback) (at Packages/com.github.kurotu.vrc-quest-tools/Editor/Models/VRChat/AvatarConverter.cs:71)
KRT.VRCQuestTools.ViewModels.AvatarConverterViewModel.ConvertAvatar (KRT.VRCQuestTools.ViewModels.AvatarConverterViewModel+CanOverwriteCallback canOverwrite, KRT.VRCQuestTools.Models.VRChat.AvatarConverter+ProgressCallback progressCallback) (at Packages/com.github.kurotu.vrc-quest-tools/Editor/ViewModels/AvatarConverterViewModel.cs:244)
KRT.VRCQuestTools.Views.AvatarConverterWindow.OnClickConvertButton () (at Packages/com.github.kurotu.vrc-quest-tools/Editor/Views/AvatarConverterWindow.cs:303)
KRT.VRCQuestTools.Views.AvatarConverterWindow.OnGUI () (at Packages/com.github.kurotu.vrc-quest-tools/Editor/Views/AvatarConverterWindow.cs:266)
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at <eae584ce26bc40229c1b1aa476bfa589>:0)
UnityEditor.HostView.Invoke (System.String methodName, System.Object obj) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.Invoke (System.String methodName) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.HostView.InvokeOnGUI (UnityEngine.Rect onGUIPosition, UnityEngine.Rect viewRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.DrawView (UnityEngine.Rect viewRect, UnityEngine.Rect dockAreaRect) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.DockArea.OldOnGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.UIElements.IMGUIContainer.DoOnGUI (UnityEngine.Event evt, UnityEngine.Matrix4x4 parentTransform, UnityEngine.Rect clippingRect, System.Boolean isComputingLayout, UnityEngine.Rect layoutSize, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, UnityEngine.Matrix4x4 worldTransform, UnityEngine.Rect clippingRect, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Action onGUIHandler, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleIMGUIEvent (UnityEngine.Event e, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.SendEventToIMGUI (UnityEngine.UIElements.EventBase evt, System.Boolean canAffectFocus) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.IMGUIContainer.HandleEvent (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.CallbackEventHandler.HandleEventAtTargetPhase (UnityEngine.UIElements.EventBase evt) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.MouseCaptureDispatchingStrategy.DispatchEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ApplyDispatchingStrategies (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, System.Boolean imguiEventIsInitiallyUsed) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEventQueue () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.OpenGate () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcherGate.Dispose () (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.ProcessEvent (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.EventDispatcher.Dispatch (UnityEngine.UIElements.EventBase evt, UnityEngine.UIElements.IPanel panel, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.BaseVisualElementPanel.SendEvent (UnityEngine.UIElements.EventBase e, UnityEngine.UIElements.DispatchMode dispatchMode) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.DoDispatch (UnityEngine.UIElements.BaseVisualElementPanel panel) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.UIElements.UIElementsUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <b6a7e1825c0b45d3b0729282e86cc687>:0)
UnityEngine.GUIUtility.ProcessEvent (System.Int32 instanceID, System.IntPtr nativeEventPtr) (at <344226e341014466b33f0c0fa34fcef5>:0)

**Used assets**
https://pastelplushiesvr.gumroad.com/l/paranoiahysteria?layout=discover&recommended_by=search

**Environment**
- VRCQuestTools version 1.11
- Unity 2019.4.31f1

**Additional context**

**Comment by kurotu** [comment]
Thank you for feedback! The error occurred because one of the textures had an unexpected format. I'll fix in the next version.

Right now, you can uncheck "Generate Textures for Quest" as a workaround. However you might meet 10MB size limit because of textures size.

![image](https://github.com/kurotu/VRCQuestTools/assets/74851548/22917bcf-d5ec-4c67-b8d3-9b3b09bcd532)

**Comment by KonstaVilkman** [comment]
Alright! Thank you for the prompt answer!

**Comment by kurotu** [comment]
The bugfix has been released as v1.12.0.
