### ISSUE TITLE
VPMService script error when update 1.12.0 installed

### ISSUE THREAD

**Issue by Kieaer** [kurotu/VRCQuestTools#13]
**Describe the bug**
Can't build, play, upload.

**To Reproduce**
Delete all folders imported with unitypackage and update to VPM.

**Expected behavior**
None.

**Screenshots**
![image](https://github.com/kurotu/VRCQuestTools/assets/44261958/11bb0e8c-9ee6-4296-aa8d-4065a944d92e)

**Console log**
``Packages\com.github.kurotu.vrc-quest-tools\Editor\Services\VPMService.cs(4,13): error CS0234: The type or namespace name 'Plastic' does not exist in the namespace 'Unity' (are you missing an assembly reference?)
``

**Used assets**
ArxCharacterShader
PumkinsAvatarTools
Thry's avatar tools
etc.

**Environment**
- VRCQuestTools version 1.12.0
- Unity 2019.4.31f1

**Additional context**
None.

**Comment by kurotu** [comment]
Thank you for feedback!

I missed that Unity.Plastic.Newtonsoft.Json.dll is optional. For now, please install **Version Control (com.unity.collab-proxy)** package from Unity Package Manager (UPM) as a workaround.

**Comment by kurotu** [comment]
v1.12.1 should fix the issue by using **NewtonSoft Json (com.unity.nuget.newtonsoft-json)**. Version Control (com.unity.collab-proxy) is no longer needed.
