### ISSUE TITLE
[Feature] Menu Option to optimize specific phybone transforms.

### ISSUE THREAD

**Issue by AraHaan** [kurotu/VRCQuestTools#14]
I have a problem with a specific VRChat Model I have where it's in fbx format and in ``prefab`` however, the option to optimize all physbones was not possible because of DPS (Deep Penetration System) rigging. However, it is possible to still be able to optimize some physbone transforms further?

This would help in cases where I might want to only optimize things like:
- Hair
- Tail
- Left Ear (assuming a furry one)
- Right Ear (assuming a furry one)
- Clothes (Oddly sometimes they also have a ton of transforms as well)

**Comment by kurotu** [comment]
Sorry, I have never used DPS and do not know how it works, so I don't know what kind of "optimization" is hoped (number of PhysBones? transform counts?). It would be helpful if you could explain specific examples and expected results.

By the way, [Anatawa12's Avatar Optimizer](https://github.com/anatawa12/AvatarOptimizer) might be helpful for PhysBones optimization. It has a component to reduce the number of PhysBones.
https://vpm.anatawa12.com/avatar-optimizer/en/docs/reference/merge-physbone/

**Comment by AraHaan** [comment]
Yeah, it would be. Would it be under a right click menu on the parent one so that way it optimizes specific ones (in a way that does not nuke DPS bones)?

**Comment by kurotu** [comment]
Thanks you for confirmation. 

> Would it be under a right click menu on the parent one so that way it optimizes specific ones
Probably yes, but right now there is no enough time to study this issue. I'm planning major update for overall conversion workflow, so I'll try to consider in this update.

And I'm not sure this would be solution for you though, PhysBone has a parameter, `Ignore Transforms` to reduce transform counts. For example, you can reduce transform counts by setting 1st child GameObject to `Ignore Transforms` in my previous screenshot. Practically same as an optimized one.

**Comment by kurotu** [comment]
Stalled issue. Now `AAO Merge Bone` component would be good choice for this use case.
https://vpm.anatawa12.com/avatar-optimizer/en/docs/reference/merge-bone/
