### ISSUE TITLE
NDMF による非破壊変換について

### ISSUE THREAD

**Issue by nekobako** [kurotu/VRCQuestTools#15]
v2.0.0 で `VQT Avatar Converter Settings` コンポーネントが追加されましたが、この設定を用いた変換をボタンによる手動ではなく Play モードに入ったとき、アバターのアップロード時、NDMF の Manual bake 時に自動で行われるようにする予定はありますでしょうか。

現状では変換結果に影響するような変更があった際、毎回手動で変換ボタンを押してからアップロードする必要があり少し手間なため、ここが自動化されるととてもありがたいです。
生成されたアセットに関しても、現状では git 管理下に置くとリポジトリの容量をひっ迫するが置かないと missing 状態になるため、どうしたものかと迷っているところです。

特にたくさんのアバターを [ContinuousAvatarUploader](https://github.com/anatawa12/ContinuousAvatarUploader) で一括アップロードしているような環境では、一括アップロード前に全アバターに対して変換ボタンを押すことになるとその利点が薄れてしまうというのもあります。

`VQT Avatar Converter Settings` コンポーネントがアタッチされているが `VQT Converted Avatar` コンポーネントがアタッチされていない場合に自動変換する、あるいは `VQT Avatar Converter Settings` コンポーネントに自動変換を行うかどうかのオプションを設けるなど、ご検討いただけますと幸いです。

**Comment by kurotu** [comment]
時期については何とも言えないのですがNDMFでの変換は追加したいと思っています。
`VQT Avatar Converter Settings` に全てを載せることができて、ようやくスタートラインに立てたというところです。

見えているところでいくつか課題があると思っていて、それぞれ検討してみないとなあという状況です。
- テクスチャ生成の速度改善 (1回きりの変換でなくNDMFの頻度だとさすがに無視できないので)
- ビルド条件・方法の使い勝手
    - テスト用にPCプラットフォームでAndroidアバターをビルドするケース
    - 変換前だと非対応アバターなのでVRCSDKのビルドボタンが無効になる問題の対処

**Comment by nekobako** [comment]
課題について確かにそうですね。。
ともかく対応自体はいずれ追加予定とのことで助かります！

**Comment by anatawa12** [comment]
> 変換前だと非対応アバターなのでVRCSDKのビルドボタンが無効になる問題の対処

については ndmf 側にもissueがあるのでそっち側での対処も期待できると思います。
(変換前だと非対応アバターなのはAAOも同様で同様の問題に直面してます) bdunderscore/ndmf#88

**Comment by kurotu** [comment]
v2.3.0で対応しました

**Comment by nekobako** [comment]
ありがとうございます・・・！！！
