### ISSUE TITLE
"Assembly has duplicate references" error due to unity bug

### ISSUE THREAD

**Issue by anatawa12** [kurotu/VRCQuestTools#17]
**Describe the bug**

Unityのバグで、GUIDでアセンブリを指定してる場合にunityがasmdefを編集してduplicate referencesを発生させてしまうことがあります。パッケージのインストール/更新時に発生することがまぁまぁあります。

Unityのバグなのですがasmdef内での参照をGUIDではなく名前で参照するようにすることで回避可能です。

```
Assembly has duplicate references: nadena.dev.ndmf (Packages/com.github.kurotu.vrc-quest-tools/Editor/NDMF/VRCQuestTools-Editor-Ndmf.asmdef)
```

<img width="636" alt="image" src="https://github.com/kurotu/VRCQuestTools/assets/22656849/6ebcb561-3fa3-4d0e-9bd3-d84434778630">

**To Reproduce**
明確な手順はないです。パッケージの更新等を繰り返し行うと発生することがあります

**Used assets**
URLs for assets you used (avatars, costumes, tools, etc.)

**Environment**
- VRCQuestTools version 2.1.1
- Unity 2019.4.31f1

**Additional context**

参考までに、他のプロジェクトもこれに関連して名前参照に切り替えてます

- BlackStartx/VRC-Gesture-Manager#36
- bdunderscore/modular-avatar#529
- anatawa12/AvatarOptimizer#649
- suzuryg/face-emo#80

**Comment by kurotu** [comment]
ツール単体としては特に問題ないので #19 はマージするのですが、新規作成したasmdefではデフォルトでGUIDを使った参照になっており、新規設計のパッケージ全てに影響する重要な不具合であるように見えます。
これに何らか関連した情報のあるページのURLなどはありますか？

**Comment by anatawa12** [comment]
> これに何らか関連した情報のあるページのURLなどはありますか？

私の知る限りだと存在しません。bug trackerでの検索でも現状見つけられていません。
