### ISSUE TITLE
Sunao Shaderに対応してほしい

### ISSUE THREAD

**Issue by zinntikumugai** [kurotu/VRCQuestTools#2]
メインで利用しているアバターがSunao Shaderなので対応お願いします

メインアバター
- [レム](https://booth.pm/ja/items/2105889)

観測したSunaoShaderを使用している無償のもの
- アバター
  - [VRChat想定オリジナル3Dモデル "スプラ”](https://booth.pm/ja/items/2598679)
  - [v1.0 VRChat想定アバター ヨルソラ](https://booth.pm/ja/items/2535468)
- 衣装
  - [ユメちゃん用肌着](https://booth.pm/ja/items/2698079)
  - [P_Store_series_05(VRC想定衣装セット)Ver1.2](https://booth.pm/ja/items/1651957)
など

**Comment by kurotu** [comment]
Closed via cf2db9f96b67e5734fbb2d4ab9be261dcfb35811, released as v0.7.0.
