### ISSUE TITLE
VQT Platform Component RemoverのUIがちょっと分かりづらい

### ISSUE THREAD

**Issue by Narazaka** [kurotu/VRCQuestTools#22]
**説明**
VQT Platform Component Removerのコンポーネント削除設定においてPCとAndroidのチェックマーク列がありますが、チェックした方が削除されるのか、チェックしない方が削除されるのか自明でなく混乱する気がします（否定の意味を表す変数は分かりづらい的なやつの事例感）。

- HelpBoxなどで補足を入れる
- 「チェックされたプラットフォームではコンポーネントを削除する」みたいな説明的な記載にする
- チェックの意味を逆転して「コンポーネントを残す」表記などにする

あたり？

**Comment by kurotu** [comment]
チェックボックスを維持と削除のどちらで使うかは作成時に迷ったところで、実動作である「削除」に合わせて「オンの時削除」としていました。少なくとも説明の追加は必要ですね。
改めて考えてみると、PhysBone Remover(オンで維持)とは逆の思考を要求するのは全体としてもイマイチな感じがしますし、チェックボックスの意味を逆転するのがよさそうかなと思います。(Platform GameObject Removerも同じく)

**Comment by kurotu** [comment]
チェックボックス反転のサンプル
Remove Mesh By BlendShape による頬染め消去を Android ビルドの時だけ実施 (⇒PCでコンポーネント削除) する使い方の例です。

![image](https://github.com/kurotu/VRCQuestTools/assets/74851548/02b0daa2-4c43-46b2-9dcd-b3b3df548935)

**Comment by kurotu** [comment]
v2.3.0で対応しました
