### ISSUE TITLE
VQT Platform Component RemoverおよびVQT Platform GameObject Removerについて、ビルドターゲットを一括上書き指定したい

### ISSUE THREAD

**Issue by Narazaka** [kurotu/VRCQuestTools#23]
**説明**
PC側においてAndroidアバターを確認したいときに、ビルドターゲットがAutoになっているものをAndroidに変えることで対処は可能ですが、いちいちコンポーネント全て変えるのは面倒です（複数編集に未対応なのでよけいに）。

- Unity Settings for Androidみたいな専用ウインドウでも出して、一括指定できるようにしたいです。
- またそもそもこのビルドターゲット指定がコンポーネント個別にSerializeFieldとして付いているのは今ひとつ用途の想像が出来ていません。コンポーネントにこの項目は不要で、グローバル指定のみでよいのではないでしょうか？

**Comment by kurotu** [comment]
> またそもそもこのビルドターゲット指定がコンポーネント個別にSerializeFieldとして付いているのは今ひとつ用途の想像が出来ていません。

これは特に理由はないですね...アバターの変換時にすべてAndroidにセットされるので気にしていなかった観点でした。
実際のところコンポーネント個別にビルドターゲットを変えることはないでしょうから、一括の指定で十分ですね。

後々のNDMFへの対応 #15 を考える点で、ビルドターゲット指定をコンポーネントとして持っておくのが良いのかなと思います。(VQT Platform Target Settingsみたいなものをアバターのルートに付ける？)

**Comment by kurotu** [comment]
取り急ぎの対応として、ビルドターゲットを一括変更するウィンドウを用意しました。Editor フォルダに保存すると`Tools/VRCQuestTools/Change Component Build Target` でウィンドウが開きます。

https://gist.github.com/kurotu/edd47ead2860f9f57262270f3d57756b

**Comment by Narazaka** [comment]
やったあ

**Comment by kurotu** [comment]
v2.3.0で Platform Target Settings を追加しました
