### ISSUE TITLE
vrcquesttools refuses to take model for conversion for quest, and I don't know why

### ISSUE THREAD

**Issue by Robbie-Smith-Jr** [kurotu/VRCQuestTools#38]
### Describe the bug / バグの説明

I'm trying to use this plugin, but dragging the model into the Avatar box doesn't work. I try to search for the model, but it's irreversibly toggled hidden. I even tried right clicking on the model to use it that way, but that doesn't work either. Not sure what else to do, but it's annoying.

### To Reproduce / 再現手順

Just trying to use the plugin produces this issue.

### Expected behavior / 期待する動作

Expected behavior is converting the duplicate of my model for quest, which it seems to be unable to do.

### Screenshots / スクリーンショット

![Screenshot 2024-11-14 194434](https://github.com/user-attachments/assets/7cfb87e1-01d4-466c-96f6-956660796cd8)

### VRCQuestTools version / VRCQuestToolsのバージョン

1.6.1, though it does this on every version.

### Unity version / Unityのバージョン

2019.4.31f1, though it does this on every version.

**Comment by kurotu** [comment]
Would you make sure that the right-clicked object has a VRCAvatarDescriptor component?

You can also use the menu bar, Tools->VRCQuestTools->Convert Avatar for Android

By the way, 1.6.1 is really too old. so I can’t support it and recommend to upgrade.

**Comment by kurotu** [comment]
Stalled issue. Closed.
