### ISSUE TITLE
生成されたテクスチャのStreaming Mip Mapsが無効になっている

### ISSUE THREAD

**Issue by zinntikumugai** [kurotu/VRCQuestTools#4]
テクスチャの生成を有効にして変換したが、生成されたテクスチャのStreaming Mip Mapsが無効になっている  
VRCのアバターとしてはひと手間増えるのでメタデータの修正を希望
(ついでに圧縮設定も継承して欲しい)

## 検証アバター 
- ベース：ディグリなす
    - シェーダー：UTS2 v2.0.7
- 小物：ヘアピン
    - シェーダー： Sunao Shader v1.4.4

**Comment by kurotu** [comment]
Streaming Mip MapsはVRCSDKのコントロールパネルで一括Auto Fixできるので優先度は低かったです

「圧縮設定」はプラットフォーム別オーバーライドのことを指していると思うのですが、念のためUnityでの表示と設定値(可能なら変換後の期待値)を教えてください (なすちゃん持っていないので)

https://docs.unity3d.com/ja/2018.4/Manual/class-TextureImporterOverride.html

Questだと実質ASTC一択・解像度は変換時に指定済みなので、わざわざ圧縮設定を引き継ぐ必要性を私が理解できていないです。

**Comment by kurotu** [comment]
Streaming Mip Maps の有効化を 2e2b3024b9becfcc3edf28103610ac1b443d66a7 で実装しました

圧縮設定については情報とともに別Issueを立ててください。具体例の列挙でもよいです

**Comment by kurotu** [comment]
v1.0.0 でリリースしたため close
