### ISSUE TITLE
テクスチャを変換すると一部の画像ファイルが変換に失敗する

### ISSUE THREAD

**Issue by zinntikumugai** [kurotu/VRCQuestTools#6]
**説明**
画像変換を行うと一部のテクスチャが全体に`？`な8x8画像が生成される(スクショ一覧参照

**再現手順**
1. Convert Avatar for Questを開く
2. アバターを選択し、変換する
3. 変換後、Sceneのアバターを確認するとテクスチャに異常があることが確認できる

エラー等は無い(Waning, Errorで、該当するエラーは確認できず)

**期待する動作**
テクスチャの変換に成功する

**スクリーンショット**

変換に失敗したテクスチャファイル
![image](https://user-images.githubusercontent.com/16275962/166144024-f90d201c-2338-4646-b1cd-f7abd994511f.png)
変換後と変換前
![image](https://user-images.githubusercontent.com/16275962/166144079-8b7de9cf-727c-48e1-b688-543f3e508d88.png)
変換後のBody(顔)のMaterial設定
![image](https://user-images.githubusercontent.com/16275962/166145247-bfae1e74-8b7c-4beb-942e-379b45a61855.png)

**追加情報**

1. 破損テクスチャファイルの変換前はほとんどPSDなのでImageMagicあたりでコケたかな?
2. (変換に失敗した影響なのか)一部の破損テクスチャファイルのファイル名が`元のファイル名_from_ハッシュ`に沿ってない
    おそらくマテリアル名

元のテクスチャファイル
![image](https://user-images.githubusercontent.com/16275962/166145389-658a247e-3906-407e-9789-6c0355c0f132.png)
破損してファイル名がおかしいテクスチャファイル
![image](https://user-images.githubusercontent.com/16275962/166145399-b75a4786-3d27-4780-8dfa-c53a1c902179.png)
左：変換後、右：変換前
![image](https://user-images.githubusercontent.com/16275962/166145463-347381ab-5b4b-47a3-af4e-d5345a0e326d.png)

**使用環境**
- Unity 2019.4.31f1
  - VRC SDK3 2022.04.21.03.29
  - VRCQuestTools 1.6.0
  - VRCDeveloperTool
  - ModelBoneDeleter 1.1.3
  - 自作のConstraintを入れ子にするやつ
  - 自作の透過系ブレンドシェイプを消すやつ
  - lilToon 1.2.12
- AFFINITY Photo 1.9.2.1035

**Comment by zinntikumugai** [comment]
試しにBody(顔)のfaceのマテリアルを`Sunao Shader/Opaque`, `Sunao Shader/Cutout `に変更して変換できたのでlilToonのBake機能と使用したPSDの相性が悪い可能性が高いかも

左　：Sunao Shader/Cutout の変換後
中央：オリジナル(Sunao Shader/Cutout)
右　：Sunao Shader/Opaque の変換後
![image](https://user-images.githubusercontent.com/16275962/166146465-cfa108c2-acdb-41da-b7a5-a4aa555a7a25.png)

**Comment by kurotu** [comment]
一度lilToon自体のベイク機能の結果を確認してみてほしいです。特にメインテクスチャ部分はlilToonのBake用シェーダーをそのまま使用しているため、lilToon自体で問題ある場合こちらでの対処が難しいです。
当面の回避策としては、手間ですがpngで書き出したテクスチャを使用してください。

> 2. (変換に失敗した影響なのか)一部の破損テクスチャファイルのファイル名が `元のファイル名_from_ハッシュ` に沿ってない
おそらくマテリアル名

これは仕様です。 `{元のマテリアル名}_from_{元のマテリアルGUID}` になります。(同じテクスチャから複数のPC版マテリアルを作成している可能性があるため)

**Comment by zinntikumugai** [comment]
`すべて焼き込み`をしたところ同様の破損テクスチャが生成されました
![image](https://user-images.githubusercontent.com/16275962/166178211-e046940f-3d0b-4ff1-b333-76d78a2ed05c.png)

Lem1.04に付属するPSDでも同様でした

liltoonのベイクですね

**Comment by zinntikumugai** [comment]
念のため別のアバターでもやってみましたが同様でした
![image](https://user-images.githubusercontent.com/16275962/166178913-9cddbbc0-9cb9-4091-a409-e158c14a5562.png)

検証アバター ：[RadDollV2](https://tonomaoo.booth.pm/items/3741802)

**Comment by zinntikumugai** [comment]
liltoonのissuesに投げます

**Comment by zinntikumugai** [comment]
liltoonの方で対応していただきました。

**Comment by zinntikumugai** [comment]
反映をお願いしたいところなんですが、注意事項にあるようにインポート設定で劣化が想定されるので、

テクスチャ.psd -> Unity Asset (圧縮設定あり) -> liltoon焼き込み -> VRCQuestTools変換

より

テクスチャ.psd -> PSDtoPNG -> liltoon焼き込み ->  VRCQuestTools変換

のほうがいいのかな？とか思ったりしてます
(少なくともインポート設定を気にしなくていいので)

**Comment by zinntikumugai** [comment]
不可逆に変換するからliltoonの焼き込み前にインポート設定を無圧縮にしてしまっても問題ないか

どれが最適解かわからんのでがんばってください(ｵｲ

**Comment by kurotu** [comment]
> テクスチャ.psd -> Unity Asset (圧縮設定あり) -> liltoon焼き込み -> VRCQuestTools変換
より、事前にPNGなどに変換して  
テクスチャ.psd -> PSDtoPNG -> liltoon焼き込み -> VRCQuestTools変換  
のほうがいいのかな？とか思ったりしてます

そうですね。実際、UTSなど他のマテリアルの変換でアセットから直接 Texture2D をロードせずに一度 ImageMagick でロードしている理由の一つは https://github.com/lilxyzw/lilToon/issues/17#issuecomment-1115166517 で触れられている劣化の回避のためです。
まったく変換がされないのは困るので、とりあえずは lilToon 同様に Texture2D でロードするようフォールバックを入れようと思います。
(長期的には lilToon 同様に専用シェーダーでのベイクに移行して ImageMagick への依存をなくしたいところだったので困り中ではあります。)

変換だけを想定するならインポート設定を無圧縮にしてもいいんですが、うっかりPCビルドでそのテクスチャを使ってしまうとビルドサイズが肥大化すると思うので、その点でもPNGで書き出したテクスチャをマテリアルに設定した方が手堅いと思います。

**Comment by kurotu** [comment]
6ba805cf35157795ac38353d7faa6a7028b5f272 で対応しました。
lilToon 同様にテクスチャがPNG/JPGでない場合はAssetDatabse.LoadAssetAtPath() でロードしますが、このとき一時的にインポート設定を書き換えてテクスチャの圧縮を無効化するようにしています。

**Comment by kurotu** [comment]
[v1.6.1](https://github.com/kurotu/VRCQuestTools/releases/tag/v1.6.1) でリリースしたためcloseします。
