### ISSUE TITLE
PhysBones Remover didn't actually remove colliders?

### ISSUE THREAD

**Issue by CrashCat** [kurotu/VRCQuestTools#9]
I used the Convert Avatar for Quest wizard on my avatar and it seems to have worked, however after the conversion it brings up the PhysBones Remover and that didnt' work entirely.  It did remove the Components down to the number I left, but even though I set it to remove all Colliders, the SDK control panel believes there are still Colliders.

![image](https://user-images.githubusercontent.com/7953195/216191774-917632b3-5aee-43de-9bac-f8ae09f443ba.png)

![image](https://user-images.githubusercontent.com/7953195/216191835-f8985a05-eb10-4a52-bdca-668749b8157a.png)

![image](https://user-images.githubusercontent.com/7953195/216191925-570be8df-1739-4ecc-90f0-535e6da90133.png)

Admittedly this doesn't matter in my case since the SDK says it's going to remove the colliders anyway, but if I did want any this is a mismatch.  Also would be nice to have an option to remove Transforms since it's complaining about that but I confess I'm out of my depth here.

**Comment by CrashCat** [comment]
Actually maybe a bit more of a problem than I thought, it says it's going to remove them but that stop sign seems to be blocking it from building the avatar.

**Comment by kurotu** [comment]
Its' weird. In this case, Phys Bone Collision Check Count should become 0.

Possibly the tool actually didn't remove some colliders, so would you show "Phys Bone Collider Count" stats of SDK? (It's different from "Phys Bone Collision Check Count".
![image](https://user-images.githubusercontent.com/74851548/216567079-2fe29526-30f5-44bd-bc20-6f5f295ed6eb.png)

And if any PhysBones still have collider settings, please show them, too.

----

I'm sure that optimizing Transform Count and Collision Check Count is not easy in current UI. I want to improve it when I have time.

**Comment by kurotu** [comment]
Recently probably I met similar situation. It's a bug so I'll fix in the next update.

**Comment by CrashCat** [comment]
I think I had an issue with Unity not refreshing.  I got the same errors again with 1.9.1 after removing the colliders:

![image](https://user-images.githubusercontent.com/7953195/219976295-0ac5854b-0e42-4c4c-9760-8ae0c59f9f6b.png)
![image](https://user-images.githubusercontent.com/7953195/219976309-0399fb44-8add-4aea-983c-189dfa6a1dc4.png)

I tried exiting and reopening project just to be sure, then they were gone: 

![image](https://user-images.githubusercontent.com/7953195/219976560-47d11abc-5359-483e-b246-2d6ca60fd41f.png)
![image](https://user-images.githubusercontent.com/7953195/219976569-59bf9732-ef8e-4eb9-81fb-cb54d98eae12.png)

This one isn't meant as a fallback so that's probably OK.  Just want people to have an option if they want to try and show it, I will be playing it on PC anyway so reduced functionality is fine.

**Comment by CrashCat** [comment]
Okay fussed with it a bit more and was able to keep some colliders.  I still don't understand why it's "2" in the remover and "64" in the Builder but maybe that's some sort of difference in units.  Also this avatar was a little hacky when I got it so there may just be some stuff thrown together wrong.

![image](https://user-images.githubusercontent.com/7953195/219977027-7a74fa29-643b-4a62-adcb-76dda2ef308f.png)
![image](https://user-images.githubusercontent.com/7953195/219977089-e0406b10-64cd-4448-8677-4ecab61d910b.png)

**Comment by CrashCat** [comment]
> Possibly the tool actually didn't remove some colliders, so would you show "Phys Bone Collider Count" stats of SDK? (It's different from "Phys Bone Collision Check Count". ![image](https://user-images.githubusercontent.com/74851548/216567079-2fe29526-30f5-44bd-bc20-6f5f295ed6eb.png)

Never mind I'm an idiot, I see where you're getting this now.  I hadn't checked the "show all avatar performance details" in the settings.  So that does show 2 which agrees with the remover.

![image](https://user-images.githubusercontent.com/7953195/219977240-fdb75a2a-4bb2-4aee-97d2-130a32921911.png)

**Comment by kurotu** [comment]
It seem that the original issue is solved. Thanks for reporting.

> I tried exiting and reopening project just to be sure, then they were gone:

Probably you **didn't convert again** with v1.9.1. The old version of converted avatar had unwanted reference to colliders of prefab asset after removing colliders in the scene. This unwanted references were made by Unity when restoring scene after play mode, so that's gone after restarting Unity. v1.9.1 is no longer using prefab asset for converted avatars, so such unwanted references never happen.
